import React, { useRef } from 'react';
import { Pause, Play, RotateCcw, Undo2 } from 'lucide-react';
import { formatTime } from './api';

export const PRESETS = {
  classic: { label: 'Universal scoreboard', scores: [1], period: 'Period', home: 'Home team', away: 'Away team' },
  basketball: { label: 'Basketball', scores: [1, 2, 3], period: 'Quarter', home: 'Home team', away: 'Away team' },
  football: { label: 'American football', scores: [1, 3, 6], period: 'Quarter', home: 'Home team', away: 'Away team' },
  soccer: { label: 'Soccer', scores: [1], period: 'Half', home: 'Home team', away: 'Away team' },
  pool: { label: 'Pool / billiards', scores: [1], period: 'Rack', home: 'Player one', away: 'Player two' },
};

export function WidgetPicker({ overlay, update }) {
  return <section className="panel widget-picker"><h2>Widget presets</h2><label className="field"><span>Sport</span><select aria-label="Scoreboard preset" value={overlay.preset || 'classic'} onChange={event => update({ preset: event.target.value })}>{Object.entries(PRESETS).map(([id, item]) => <option value={id} key={id}>{item.label}</option>)}</select></label><label className="field"><span>Graphic</span><select aria-label="Graphic layout" value={overlay.graphicMode || 'scoreboard'} onChange={event => update({ graphicMode: event.target.value })}><option value="scoreboard">Live scorebug</option><option value="matchup">Matchup / intermission card</option></select></label><p>Live controls below update your video instantly.</p></section>;
}

function Counter({ label, value, change, max = 99 }) { return <div className="detail-counter"><span>{label}</span><div><button aria-label={`Decrease ${label}`} onClick={() => change(Math.max(0, value - 1))}>−</button><output>{value}</output><button aria-label={`Increase ${label}`} onClick={() => change(Math.min(max, value + 1))}>+</button></div></div>; }

export function SportControls({ overlay, update, seconds, setSeconds, clockRunning, setClockRunning, clockMode, setClockMode }) {
  const preset = PRESETS[overlay.preset] || PRESETS.classic;
  const history = useRef([]);
  function score(team, delta) { history.current.push({ homeScore: overlay.homeScore, awayScore: overlay.awayScore }); if (history.current.length > 50) history.current.shift(); update({ [`${team}Score`]: Math.max(0, Math.min(999, overlay[`${team}Score`] + delta)) }); }
  return <section className="panel match-panel"><div className="section-heading"><h2>Match controls</h2><button className="icon-button" title="Undo last score" aria-label="Undo last score" onClick={() => { const previous = history.current.pop(); if (previous) update(previous); }}><Undo2/></button></div><div className="team-grid">{['home', 'away'].map(team => <div key={team}><label className="field"><span>{preset[team]}</span><input aria-label={`${team} team name`} maxLength="24" value={overlay[team]} onChange={e => update({ [team]: e.target.value })}/></label><div className="stepper"><button aria-label={`Decrease ${team} score`} onClick={() => score(team, -1)}>−</button><output>{overlay[`${team}Score`]}</output><button aria-label={`Increase ${team} score`} onClick={() => score(team, 1)}>+</button></div>{preset.scores.length > 1 && <div className="score-shortcuts">{preset.scores.map(points => <button key={points} aria-label={`Add ${points} to ${team} score`} onClick={() => score(team, points)}>+{points}</button>)}</div>}</div>)}</div>
    {overlay.preset === 'basketball' && <div className="sport-details"><Counter label="Home fouls" value={overlay.homeFouls || 0} change={value => update({ homeFouls: value })} max={9}/><Counter label="Away fouls" value={overlay.awayFouls || 0} change={value => update({ awayFouls: value })} max={9}/></div>}
    {overlay.preset === 'football' && <div className="sport-details"><label className="field"><span>Down</span><select aria-label="Down" value={overlay.down || 1} onChange={e => update({ down: Number(e.target.value) })}>{[1, 2, 3, 4].map(down => <option key={down} value={down}>{down}</option>)}</select></label><label className="field"><span>Yards to go</span><input aria-label="Yards to go" type="number" min="0" max="99" value={overlay.distance ?? 10} onChange={e => update({ distance: Number(e.target.value) })}/></label></div>}
    {overlay.preset === 'pool' && <label className="field pool-race"><span>Race to</span><input aria-label="Race to" type="number" min="1" max="99" value={overlay.raceTo || 7} onChange={e => update({ raceTo: Number(e.target.value) })}/></label>}
    {['basketball', 'football', 'pool'].includes(overlay.preset) && <label className="field possession"><span>{overlay.preset === 'pool' ? 'At the table' : 'Possession'}</span><select aria-label="Possession" value={overlay.possession || 'none'} onChange={e => update({ possession: e.target.value })}><option value="none">None</option><option value="home">{overlay.home}</option><option value="away">{overlay.away}</option></select></label>}
    <div className="clock-grid"><label className="field"><span>{preset.period}</span><input aria-label="Period or rack" maxLength="12" value={overlay.period} onChange={e => update({ period: e.target.value })}/></label><div><span className="field-label">Clock</span><strong className="clock">{formatTime(seconds)}</strong><div className="clock-actions"><button onClick={() => setClockRunning(!clockRunning)}>{clockRunning ? <Pause/> : <Play/>}{clockRunning ? 'Pause' : 'Start'}</button><button className="icon-button" aria-label="Reset clock" onClick={() => { setClockRunning(false); setSeconds(0); }}><RotateCcw/></button></div></div></div><div className="sport-details clock-settings"><label className="field"><span>Clock mode</span><select disabled={clockRunning} aria-label="Clock mode" value={clockMode} onChange={e => setClockMode(e.target.value)}><option value="up">Count up</option><option value="down">Count down</option></select></label><label className="field"><span>Set minutes</span><input aria-label="Set clock minutes" type="number" min="0" max="999" step=".5" disabled={clockRunning} value={Math.round(seconds / 60 * 100) / 100} onChange={e => setSeconds(Math.max(0, Math.round(Number(e.target.value) * 60)))}/></label></div><label className="toggle-row"><span>Show scoreboard</span><input type="checkbox" role="switch" checked={overlay.visible} onChange={e => update({ visible: e.target.checked })}/><span className="switch" aria-hidden="true"/></label>
  </section>;
}
