#!/data/data/com.termux/files/usr/bin/bash
# Install a one-tap Termux home-screen shortcut to launch RIVET.
set -euo pipefail
umask 077

usage() {
  cat <<'USAGE' >&2
Usage: bash install-rivet-shortcut.sh [--name NAME] [--open]
Usage: bash install-rivet-shortcut.sh [--name NAME] [--no-open]

Creates ~/.shortcuts/<NAME> when run on Termux.

Options:
  --name NAME     Override shortcut file/name (default: RIVET)
  --no-open       Create a shortcut that starts service without opening the browser
  --open          Explicitly open the browser after launch (default)
  --help, -h      Show usage
USAGE
}

name="RIVET"
open_browser=true

while [[ $# -gt 0 ]]; do
  case "$1" in
    --name)
      shift
      if [[ $# -eq 0 || -z "$1" ]]; then
        usage
        exit 2
      fi
      name="$1"
      ;;
    --no-open)
      open_browser=false
      ;;
    --open)
      open_browser=true
      ;;
    --help|-h)
      usage
      exit 0
      ;;
    --*)
      usage
      exit 2
      ;;
    *)
      usage
      exit 2
      ;;
  esac
  shift
done

if [[ -z "${PREFIX:-}" || -z "${HOME:-}" ]]; then
  echo 'Run this inside Termux.' >&2
  exit 1
fi

if [[ ! -x "$HOME/start-rivet" ]]; then
  echo 'RIVET launcher not found. Install first with install-rivet-termux.sh.' >&2
  exit 1
fi

safe_name="${name// /_}"
safe_name="${safe_name//[^A-Za-z0-9._-]/_}"
if [[ -z "$safe_name" ]]; then
  safe_name="RIVET"
fi

shortcut_dir="$HOME/.shortcuts"
mkdir -p "$shortcut_dir"
chmod 700 "$shortcut_dir"

shortcut="$shortcut_dir/$safe_name"
if [[ -e "$shortcut" ]]; then
  printf 'A shortcut named %s already exists and will be replaced.\n' "$safe_name"
fi

if [[ "$open_browser" == true ]]; then
  opener=''
else
  opener='--no-open'
fi

cat > "$shortcut" <<EOF
#!/data/data/com.termux/files/usr/bin/bash
# Generated by install-rivet-shortcut.sh
set -euo pipefail

export PREFIX=/data/data/com.termux/files/usr
export HOME=/data/data/com.termux/files/home
export PATH="$PREFIX/bin:/system/bin:/system/xbin"
export LD_PRELOAD="$PREFIX/lib/libtermux-exec.so"
mkdir -p "$HOME/.local/state/rivet"
nohup "$HOME/start-rivet" ${opener} >"$HOME/.local/state/rivet/shortcut.log" 2>&1 </dev/null &
EOF

chmod 700 "$shortcut"

echo "Shortcut created: $shortcut"
echo "Use this label on your home screen shortcut: $safe_name"

if command -v cmd >/dev/null 2>&1; then
  if cmd package list packages com.termux.widget | grep -q 'package:com.termux.widget'; then
    echo "Termux:Widget is installed. Add the Termux:Widget widget and tap '$safe_name'."
  else
    echo "Termux:Widget is not installed, so the script is ready but no widget entry can be shown yet."
    echo "Install Termux:Widget, then open it and add this shortcut."
  fi
else
  echo "Termux:Widget not detected via 'cmd'. If installed, add a widget for 'Termux:Widget'."
fi

if [[ "$opener" == --no-open ]]; then
  echo "This shortcut starts background service only. Open the browser manually when ready."
else
  echo "This shortcut starts RIVET and opens the studio page in the current browser if available."
fi
